### ISSUE TITLE
각자 시나리오 만들어 보기 

### ISSUE THREAD

**Issue by niceaji** [jeju242/about#1]
- 서비스에 필요한 화면을 직접 그려봅니다.

**Comment by claraqn** [comment]
1. 각자 서비스기획 및 시나리오 만들어보고 issue에 추가
2. 추가된 내용으로 2021-01-07 16:00 회의시간에 의견나누기

**Comment by claraqn** [comment]
![KakaoTalk_20210107_011709642](https://user-images.githubusercontent.com/37091625/103791790-3762e580-5086-11eb-8163-a8be8c6b74f4.jpg)
![KakaoTalk_20210107_011709642_01](https://user-images.githubusercontent.com/37091625/103791806-3c279980-5086-11eb-98ed-ed7635242689.jpg)

**Comment by niceaji** [comment]
@claraqn 깔끔하게 잘 만드셨네요 👍

**Comment by qww1552** [comment]
이용자 : 비대면 상황으로인해 학교지리에 익숙하지 않은 재학생(20학번) 및 신입생, 편입생

![슬라이드1](https://user-images.githubusercontent.com/62738554/103851201-86436600-50ec-11eb-8086-198d03d3a223.JPG)
![슬라이드2](https://user-images.githubusercontent.com/62738554/103851233-9f4c1700-50ec-11eb-8997-c248e7f5c829.JPG)
![슬라이드3](https://user-images.githubusercontent.com/62738554/103851237-a1ae7100-50ec-11eb-9c85-0dc64b6bca81.JPG)

**Comment by hyunjunyong** [comment]
주 연령층은 : 10대후반 ~ 20대중반 + 예외적으로 축제시즌, 벚꽃시즌에 찾아오는 방문객들
기대효과 : 유저들에게 효과적인 정보 제공
<img width="960" alt="시나리오 1" src="https://user-images.githubusercontent.com/26618280/103857918-be51a580-50fa-11eb-9934-4886620e1e18.png">
<img width="960" alt="시나리오 2" src="https://user-images.githubusercontent.com/26618280/103857921-bf82d280-50fa-11eb-8c66-0266f43cd049.png">
<img width="960" alt="시나리오 3" src="https://user-images.githubusercontent.com/26618280/103857939-c4478680-50fa-11eb-9b06-04a70559671c.png">

**Comment by hshk1004** [comment]
이용자: 10대 후반~ 20대 초반 그 외 벛꽃이나 눈을 보러오는 관광객

만든 배경과 목적: 학교 홈페이지의 줄글 설명을 읽기 힘들다. 설명문으로는 학교의 전체적 구조와 자신이 원하는 건물의 위치가 명확하게 확인하기 힘들다.  그에 따라 학교의 구역과 건물의 명칭을 표시, 학교 건물의 위치를 시각적으로 확인 하게 쉽게 만들고 각 건물과 층별 설명을 넣어 유저가 편리하게 정보를 얻을수 있게 한다.

사이트의 첫 화면과 그에 따른 기능과 페이지 설명도
![242fosillsinario](https://user-images.githubusercontent.com/26293574/103859565-99aafd00-50fd-11eb-8df9-661b1d108f2c.jpg)
