### ISSUE TITLE
단과대별 학과와 설명-내용 논의 필요

### ISSUE THREAD

**Issue by hshk1004** [jeju242/about#17]
- [ ] 커스텀 오버레이 리스트 생성(json파일)-스타일 논의 필요

- [x] 설명 리스트(태그포함) 생성(json파일)

- [x] 단과대별 학과 리스트 생성

- [x] 학과 클릭시 맵으로 스크롤(사이트 이동) 하기

- [ ] 맵 중심 각 학과에 맞는 좌표로 이동

- [ ] 학과에 맞는 오버레이 생성

- [ ] 학과에 맞는 설명 생성

**Comment by hshk1004** [comment]
커스텀 오버레이 논의사항

1.건물의 층별 정보를 담을 것인가

2.건물의 학과별 정보를 담을 것인가

    2-1.건물의 학과별 정보를 담을때, 학과 사무실이 없는 층은 어떻게 할것인가

    2-2.건물의 학과별 정보를 담을때, 층에 학과 사무실이 없는 층은 어떻게 할것인가

3.건물 자료조사 이슈의 건물의 정보중 강의실만 있는 건물에 관하여 강의실 명을 넣을 것인가

4.건물 자료조사 한것들의 사진을 사용할 것인가

    4-1.건물 자료조사 한것들의 사진을 사용할경우, 건물의 사진을 커스텀 오버레이의 배경에 넣을 것인가

    4-2.건물 자료조사 한것들의 사진을 사용할 경우, 건물의 사진을 설명창 배경에 넣을 것인가

5.현 jeju242.github.io의 커스텀 오버레이의 스타일을 변경할 경우 깔끔하게 보이기 위해 그림을 사용할 것인가

예)
![맵 커스텀오버레이 시안](https://user-images.githubusercontent.com/26293574/105391976-01188f00-5c5e-11eb-9deb-429733a86f48.PNG)

@qww1552 @hyunjunyong @claraqn

**Comment by claraqn** [comment]
<혜원 의견>
2-1.건물의 학과별 정보를 담을때, 학과 사무실이 없는 층은 어떻게 할것인가
2-2.건물의 학과별 정보를 담을때, 층에 학과 사무실이 없는 층은 어떻게 할것인가
==>일단 제외?
3.건물 자료조사 이슈의 건물의 정보중 강의실만 있는 건물에 관하여 강의실 명을 넣을 것인가
==>강의실만 있는 건물에 관하여 강의실 명을 넣지 않는다. 커스텀 오버레이에 층 모두 '강의실'이라고만 표기
4.건물 자료조사 한것들의 사진을 사용할 것인가
4-1.건물 자료조사 한것들의 사진을 사용할경우, 건물의 사진을 커스텀 오버레이의 배경에 넣을 것인가
4-2.건물 자료조사 한것들의 사진을 사용할 경우, 건물의 사진을 설명창 배경에 넣을 것인가
==>커스텀 오버레이에 넣으면 사진크기가 너무 작지 않을까? 어떤 건물인지 구분할 수 없다면 설명창 한표.
5.현 jeju242.github.io의 커스텀 오버레이의 스타일을 변경할 경우 깔끔하게 보이기 위해 그림을 사용할 것인가
==>예시 좋아요 찬성

**Comment by hyunjunyong** [comment]
커스텀 오버레이 논의사항

1.건물의 층별 정보를 담을 것인가

-> 무슨 뜻인지 ???

2.건물의 학과별 정보를 담을 것인가

2-1.건물의 학과별 정보를 담을때, 학과 사무실이 없는 층은 어떻게 할것인가

2-2.건물의 학과별 정보를 담을때, 층에 학과 사무실이 없는 층은 어떻게 할것인가

->각 층의 학과 사무실이 몰려있으면 차라리 처음 커스텀 오버레이에 층을 없애고 학과만 적는건 어떤지?

3.건물 자료조사 이슈의 건물의 정보중 강의실만 있는 건물에 관하여 강의실 명을 넣을 것인가
-> 대강당,(간호학과에 실험실)등의 특수한 강의실만 넣고, 추가로 특수한 과만 이용하는 강의실만 적는게 좋을 것같음 모든 강의실을 넣는건 불필요하다고 생각

4.건물 자료조사 한것들의 사진을 사용할 것인가

4-1.건물 자료조사 한것들의 사진을 사용할경우, 건물의 사진을 커스텀 오버레이의 배경에 넣을 것인가

4-2.건물 자료조사 한것들의 사진을 사용할 경우, 건물의 사진을 설명창 배경에 넣을 것인가
->사진을 사용하고 4-2의 방법이 더 괜찮을거 같음

5.현 jeju242.github.io의 커스텀 오버레이의 스타일을 변경할 경우 깔끔하게 보이기 위해 그림을 사용할 것인가
->찬성

**Comment by qww1552** [comment]
커스텀 오버레이 논의사항

3.건물 자료조사 이슈의 건물의 정보중 강의실만 있는 건물에 관하여 강의실 명을 넣을 것인가
-> 2-1, 2-2, 3 강의실이나 실습실 등 별 특징 없는 방들만 있으면 저번에 찍어온 층별안내도 보여주는건 어떨까 싶음

4.건물 자료조사 한것들의 사진을 사용할 것인가
-> 층별안내도는 3번 처럼 활용하고 
-> 설명창에 전경사진 올리는게 괜찮을 듯함

5.현 jeju242.github.io의 커스텀 오버레이의 스타일을 변경할 경우 깔끔하게 보이기 위해 그림을 사용할 것인가
-> 오버레이 디자인은 바꿔야돼 저거 내가 그냥 임시로 넣은거
