### ISSUE TITLE
페이스북 좋아요 버튼 연동

### ISSUE THREAD

**Issue by claraqn** [jeju242/about#22]
### 전체화면
![image](https://user-images.githubusercontent.com/37091625/105724512-47763280-5f6b-11eb-9e92-024011d7e587.png)
>좋아요 버튼 눌리지 않음

### 줄어든화면
![image](https://user-images.githubusercontent.com/37091625/105724629-64ab0100-5f6b-11eb-9f25-0226e62002df.png)
>좋아요 버튼 눌림

>>>>이유?

**Comment by claraqn** [comment]
<div id="fb-root"></div>
							<script async defer crossorigin="anonymous" 
								src="https://connect.facebook.net/ko_KR/sdk.js#xfbml=1&version=v9.0" 
								nonce="ZCmcHGTF">
							</script>
							<div class="fb-like" 
								data-href="http://jeju242.github.io/" 
								data-width="" 
								data-layout="button_count" 
								data-action="like" 
								data-size="large" 
								data-share="false">
							</div>

**Comment by claraqn** [comment]
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" 
	src="https://connect.facebook.net/ko_KR/sdk.js#xfbml=1&version=v9.0" 
	nonce="ZCmcHGTF">
</script>
<div class="fb-like" 
	data-href="http://jeju242.github.io/" 
	data-width="" 
	data-layout="button_count" 
	data-action="like" 
	data-size="large" 
	data-share="false">
</div>

**Comment by claraqn** [comment]
`<div id="fb-root"></div>
							<script async defer crossorigin="anonymous" 
								src="https://connect.facebook.net/ko_KR/sdk.js#xfbml=1&version=v9.0" 
								nonce="ZCmcHGTF">
							</script>
							<div class="fb-like" 
								data-href="http://jeju242.github.io/" 
								data-width="" 
								data-layout="button_count" 
								data-action="like" 
								data-size="large" 
								data-share="false">
							</div>`

**Comment by claraqn** [comment]
`<div id="fb-root"></div>
							<script async defer crossorigin="anonymous" 
								src="https://connect.facebook.net/ko_KR/sdk.js#xfbml=1&version=v9.0" 
								nonce="ZCmcHGTF">
							</script>
							<div class="fb-like" 
								data-href="http://jeju242.github.io/" 
								data-width="" 
								data-layout="button_count" 
								data-action="like" 
								data-size="large" 
								data-share="false">
							</div>`

**Comment by claraqn** [comment]
![image](https://user-images.githubusercontent.com/37091625/105879832-fc7d1d80-6045-11eb-93f7-79a7eec9272e.png)

_버튼추가 완료!_

**Comment by niceaji** [comment]
@claraqn 좋아요 100개 갑시다 ㅎ
