### ISSUE TITLE
댓글창 중복

### ISSUE THREAD

**Issue by hyunjunyong** [jeju242/about#24]
<img width="960" alt="초기 교양동 클릭시 댓글창" src="https://user-images.githubusercontent.com/26618280/105820862-75a45280-5ffd-11eb-8ca7-5aa1c543b6a9.png">
<img width="960" alt="이후 공4클릭시 댓글창" src="https://user-images.githubusercontent.com/26618280/105820880-7b9a3380-5ffd-11eb-8f21-3c626522081e.png">
초기 교양동 마커를 클릭해서 ㅎㅇ라는 댓글을 생성해서 공대4호관 마커 클릭시 댓글창이 초기화되어야 하는데 아직 되지않음
수정중

**Comment by qww1552** [comment]
Threads contain comments. A thread is associated with a page which has Disqus embedded. For example, a page located at http://example.com/my-blog-post.html will have one unique thread associated with that page. This thread will contain all of the comments on the page, as well as everything else that is relevant to that instance of Disqus (such as likes, participating users, and other metadata). **_Threads are uniquely identified by either a page-provided identifier or a URL._**

출처: https://help.disqus.com/en/articles/1717050-how-does-disqus-work
댓글창은 url당 하나씩 구분된다는 듯
밑에것도 비슷한 내용
http://astrod.github.io/etc/2016/03/27/github+jekyll%EB%B8%94%EB%A1%9C%EA%B7%B8%EC%97%90-disqus-%EC%A0%81%EC%9A%A9-%EC%82%BD%EC%A7%88%EA%B8%B0/

**Comment by hyunjunyong** [comment]
https://github.com/disqus/DISQUS-API-Recipes/blob/master/snippets/js/disqus-reset/disqus_reset.html
멘토님이 알려주신 사이트랑 이사이트랑 추가로해서 수정중 위에 코멘트도 다 확인했었던건데 결국 url이 같으니깐 해결법 새로 찾고있을께

**Comment by niceaji** [comment]
@hyunjunyong  
https://myeongjae.kim/blog/2018/10/05/%EC%9B%B9-spa%EC%97%90%EC%84%9C-disqus-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0
여기서 댓글창을 불러올때마다 (다른곳을 클릭할때마다) initDisqus() 해주면 되지 않나요?

**Comment by qww1552** [comment]
![image](https://user-images.githubusercontent.com/62738554/105953197-1ce4c080-60b6-11eb-903e-9f9815c8fc18.png)
마커당 하나씩 댓글창을 구분하고 싶은데

**Comment by qww1552** [comment]
@hyunjunyong 
![image](https://user-images.githubusercontent.com/62738554/105954756-7ea62a00-60b8-11eb-87f7-f8ca19556e98.png)
![image](https://user-images.githubusercontent.com/62738554/105954778-8960bf00-60b8-11eb-8285-401056f9d58a.png)


![image](https://user-images.githubusercontent.com/62738554/105955972-6f27e080-60ba-11eb-8805-d1306dca4379.png)

```javascript
initDisqus('http-127-0-0-1-5500-1',place.place_name,place.place_name,'http://127.0.0.1:5500/about/map.html'+'/'+place.place_name);
```

마커 클릭이벤트에 위 코드 넣으니까 동작은 하는데 충돌이 좀 생기나봐요. 몇몇 건물들은 댓글창 구분이 안됩니다.

**Comment by hyunjunyong** [comment]
<img width="960" alt="수정3" src="https://user-images.githubusercontent.com/26618280/105958222-aa77de80-60bd-11eb-8d09-ece22fe8ab54.png">
<img width="960" alt="수정2" src="https://user-images.githubusercontent.com/26618280/105958225-ac41a200-60bd-11eb-9e19-f3f7d5d795e6.png">
<img width="960" alt="수정1" src="https://user-images.githubusercontent.com/26618280/105958227-acda3880-60bd-11eb-8f91-97d22525a0fb.png">
<img width="960" alt="수정" src="https://user-images.githubusercontent.com/26618280/105958228-acda3880-60bd-11eb-8fc4-7696cce3b039.png">
<button onclick="reset('newid1', 'https://project-jeju.disqus.com/embed.js');">Load article 1</button>
    <button onclick="reset('newid2', 'https://project-jeju.disqus.com/embed.js1');">Load article 2</button>
    <button onclick="reset('newid3', 'https://project-jeju.disqus.com/embed.js2');">Load article 3</button>
    <button onclick="reset('newid4', 'https://project-jeju.disqus.com/embed.js3');">Load article 4</button>
연습용 코드로 먼저 따로 시도한건데 이 부분은 되길래 마커를 클릭이벤트에 리셋함수 추가하고 마커에 추가해봐야 될거 같음

**Comment by hyunjunyong** [comment]
<img width="960" alt="수정2차 2" src="https://user-images.githubusercontent.com/26618280/105966232-b8caf800-60c7-11eb-9748-7e3da8f34c55.png">
<img width="960" alt="수정2차 1" src="https://user-images.githubusercontent.com/26618280/105966236-ba94bb80-60c7-11eb-85f6-13c35a0e2f7f.png">
<img width="960" alt="수정2차" src="https://user-images.githubusercontent.com/26618280/105966238-ba94bb80-60c7-11eb-9414-df8e0976b31b.png">
일단은 진행 되는거 같고 코드 깃풀로 올릴테니깐 확인부탁 quizhj
