### ISSUE TITLE
PPT 진적도

### ISSUE THREAD

**Issue by hshk1004** [jeju242/about#26]
발표 시나리오

- [x] 인사

팀명-jeju242fosills
멘토 - 강XX 
준용, 혜원, 민성, 나

- [x] 프로젝트 주제

제주대학교 소개하는 웹페이지

기획 의도 - 신입생 편입생 재학생 잘 모르는곳이 많음

서비스 - 제주대학교 건물들 알려주는 페이지, 제주대에 관한 흥미를 위한 퀴즈 페이지

기능설명 - 페이지로 이동

첫 페이지 - 서비스 설명

맵 페이지 - 제주대학교 건물에 관하여 설명

퀴즈 페이지 - 학교에 관한 문제 15가지 다 진행된뒤 맞춘 비율에 따라 다른 캐릭터 표시

어바웃 어스 - 넘기고 깃허브로 넘어감

- [x] 멘토님에게 배운것

깃허브 현업에 관한것 - 이슈사용, 위키에 관한것, 서비스가 마스터이다, 작업시 마스터가 아닌 브랜치에서 작업한다. 

- [x] 소감

순서대로

**Comment by niceaji** [comment]
@hshk1004  멘토에게 배운거를 정리한다기보다 ㅎ  웹페이지에도 작성하셨든  팀프로젝트를 비대면으로 github,카톡,meet등으로 진행해본 경험에 대해서 풀어보면 어떨까요?

**Comment by hshk1004** [comment]
발표 진행 흐름 사항

피피티 시작

슬라이드 1 - 간략한 소개 - 현장실습 4조 멘토 강순범, 멘티 오민성, 나, 현준용, 임혜원 팀 jeju242fossils 발표 시작. 만든것- 제주대소개사이트

슬2 - 계기 - 신입생은 코로나로 잘 모름, 편입생도 처음 오는 사람들도 잘 모름, 재학생 잘 가지 않아 모르는곳 많음 알려주기

슬3- 구성 소개 - 소개 사이트는 누굴 위한것인지, 어떤것을 사용했는지, 그냥 지도와 다른점이 무엇인지

피피티 아웃(4로 넘어간 상태)

웹페이지 인

홈페이지 - 서비스 이용자 안내

맵 - 구역을 클릭했을때 건물에 마커 표시, 오버레이 클릭시 설명 표시, 건물마다 다른 댓글창 구현

어바웃 어스 - 팀명 설명, 각자 파트 설명, 개발 과정 설명

퀴즈 - 15문제, 답 선택시 초록, 오답 선택시 빨강 그리고 정답 초록

웹페이지 아웃

피피티 인(4부터)

4슬 - 퀴즈 결과 안내 - 점수별 다른 캐릭터로 시각적 표현

5슬 - 비대면 협업으로 배운것 - 개인과 다르게 단체를 만들어 사용하는것

6슬 - 비대면으로 배운것 - 마스터 외 다른 브랜치에서 작업후 마스터 머지

7슬 - 이슈 사용으로 일에 대하여 소통

8슬 - 작업물에 대한 중요한것 위키로 만듬

9슬 - 위키의 최종 명세서 - 이슈에서 만들어서 정리한것 위키로 이동

10슬 - 위키 최종 시나리오 - 앞에서 설명한것 대부분 적용됨

11슬 - 현재 개발, 테스트, 오픈 진행됨 마케팅과 유지 필요

12슬 - 소감 김한승먼저 이후 -> 순서대로

13슬 - 질문?

**Comment by claraqn** [comment]
소감
1. 김한승
2. 임혜원
3. 오민성
4. 현준용

**Comment by qww1552** [comment]
3.오민성

**Comment by hyunjunyong** [comment]
마지막
