### ISSUE TITLE
기능 명세서 만들어보기

### ISSUE THREAD

**Issue by claraqn** [jeju242/about#5]
각자 지도, 퀴즈에 관한 기능 명세서 만들어 올리고 1/12 14:00 회의에서 최종 기능 명세서 선택(이후 16:00 멘토님과의 회의에서 발표)

**Comment by claraqn** [comment]
![기능명세서](https://user-images.githubusercontent.com/37091625/104210647-78883a80-5476-11eb-8cda-419a588cf29f.png)

**Comment by claraqn** [comment]
<img width="802" alt="기능명세서" src="https://user-images.githubusercontent.com/37091625/104210943-d3219680-5476-11eb-9482-80f20131f179.png">

**Comment by hyunjunyong** [comment]
<img width="678" alt="기능 명세서" src="https://user-images.githubusercontent.com/26618280/104223779-6cf13f80-5487-11eb-818e-4d4491e9b9ea.png">

**Comment by hyunjunyong** [comment]
![Uploading 기능 명세서.png…]()

**Comment by hyunjunyong** [comment]
![Uploading 기능 명세서.png…]()

**Comment by hyunjunyong** [comment]
<img width="494" alt="기능 명세서" src="https://user-images.githubusercontent.com/26618280/104268338-03991d00-54d7-11eb-9f64-305f08c116f6.png">

**Comment by hshk1004** [comment]
![기능명세서1](https://user-images.githubusercontent.com/26293574/104271312-f6336100-54dd-11eb-8822-1a44c8840da9.PNG)
![기능명세서2](https://user-images.githubusercontent.com/26293574/104271314-f7648e00-54dd-11eb-8f3e-38ffbfffed85.PNG)

**Comment by hyunjunyong** [comment]
<img width="488" alt="기능명세서 합" src="https://user-images.githubusercontent.com/26618280/104275163-a9538880-54e5-11eb-8770-8b5f322ab522.png">

**Comment by claraqn** [comment]
<img width="488" alt="104275163-a9538880-54e5-11eb-8770-8b5f322ab522" src="https://user-images.githubusercontent.com/37091625/104734180-2fd8c600-5783-11eb-9b53-9625060564af.png">
