### ISSUE TITLE
각자 마스코트 그려와보기

### ISSUE THREAD

**Issue by claraqn** [jeju242/about#7]
각자 퀴즈 결과 부분에 추가될 마스코트 그려와보기(3가지 모습)
->원래는 제주대학교 홈페이지에 있는 마스코트를 그대로 쓸 예정이었는데 사용자들의 시각적 재미를 위해 각자 만들어보기로 함!!🤣

**Comment by claraqn** [comment]
![Uploading 돌이.png…]()

**Comment by claraqn** [comment]
![돌이](https://user-images.githubusercontent.com/37091625/104186102-3f8d9d00-5459-11eb-802a-f32c527449ed.png)

**Comment by hyunjunyong** [comment]
멘트 차후추가..... 최선을 다해서 그린...
![마스코트 그림_LI](https://user-images.githubusercontent.com/26618280/104714732-ef6c4e80-5768-11eb-8afc-55e18f70acab.jpg)

**Comment by hshk1004** [comment]
손글씨 상태가 좋지 않아 멘트 손글씨 좋은 사람걸로...

![마스코트 초안](https://user-images.githubusercontent.com/26293574/105403541-37f5a180-5c6c-11eb-96c5-ae44b30d54db.png)
