### ISSUE TITLE
제주대학교 건물 자료조사

### ISSUE THREAD

**Issue by hyunjunyong** [jeju242/about#9]
[자료조사 리스트.pptx](https://github.com/jeju242/about/files/5807505/default.pptx)

**Comment by qww1552** [comment]
![슬라이드2](https://user-images.githubusercontent.com/62738554/104446016-30cff300-55dd-11eb-8ef9-b9c880b2c3ae.JPG)
![슬라이드3](https://user-images.githubusercontent.com/62738554/104446057-3e857880-55dd-11eb-87bc-5298a5bafc42.JPG)
![슬라이드6](https://user-images.githubusercontent.com/62738554/104446073-4513f000-55dd-11eb-8fe2-ec12649dba74.JPG)
![슬라이드7](https://user-images.githubusercontent.com/62738554/104446078-46451d00-55dd-11eb-8bd8-c9f0215472fe.JPG)
![슬라이드8](https://user-images.githubusercontent.com/62738554/104446079-46451d00-55dd-11eb-813d-eb3a630f0054.JPG)
![슬라이드9](https://user-images.githubusercontent.com/62738554/104446080-46ddb380-55dd-11eb-895c-a26f26620e14.JPG)
![슬라이드10](https://user-images.githubusercontent.com/62738554/104446082-46ddb380-55dd-11eb-9536-6509b99ed344.JPG)
![슬라이드11](https://user-images.githubusercontent.com/62738554/104446088-480ee080-55dd-11eb-8e09-c9bf0438a56c.JPG)
![슬라이드12](https://user-images.githubusercontent.com/62738554/104446090-480ee080-55dd-11eb-8e43-51faa38a560d.JPG)
![슬라이드4](https://user-images.githubusercontent.com/62738554/104446094-48a77700-55dd-11eb-9f7d-cfcc13d9a8dc.JPG)
![슬라이드5](https://user-images.githubusercontent.com/62738554/104446096-49400d80-55dd-11eb-8655-e584cec92457.JPG)

사진이 몇개 빠져있는데 시간날 때 채워넣겠습니다.

**Comment by claraqn** [comment]
[건물사진및층별정리.pdf](https://github.com/jeju242/about/files/5808821/default.pdf)

**Comment by niceaji** [comment]
@qww1552 @claraqn  직접 찍으신건가요? 눈온사진이라 최근 같은데요? ㅎ

**Comment by claraqn** [comment]
@niceaji 넵! 어제 다같이 모여서 구역별로 돌아다니면서 사진 찍었어요 :)

**Comment by hshk1004** [comment]
![본관1](https://user-images.githubusercontent.com/26293574/104823400-1cb21d00-588d-11eb-97b9-34c8c2026247.jpg)

본관

1층-아라홀, JOB CAFE, 학생상담센터, 우편 취급소, 진로취업과 ,일자리센터, 입학 본부장실, 학사과, 입학본부, 입학관리과, 문서창고, 당직실, 제정과, 총무과, 전화기계실, 교통상황실, 우편실, 학생지원 종합서비스 센터, 농협

2층-대학원 행정실, 제주녹색환경지원센터, 제주씨그린트센터, 냉난방통합 관제센터, 평화연구소, 인권센터, 예비군 연대, 총장실, 부총장실, 교무처장실, 사무국장실, 기획처장실, 교무과, 기획평가과, 시설과, 설계실

3층-제대교육방송, 제주대 신문, 영자신문, 지식재산교육센터, 대학노조, R&D전략센터, 산학협력과, 연구지원과, 학생복지과, 새싹 봉사 본부, 제주국제개발 협력센터, 홍보출판문화원, 학생홍보 대사실, 교류추진실(나가사키대학)

4층-보존서고, 부속 서고


![사범대1,2호관](https://user-images.githubusercontent.com/26293574/104823404-276cb200-588d-11eb-9de0-345953117d5e.jpg)

사범대학1호관

1층-천체물리 실험실, 과학교육학부, 전자기학/ 현대물리 실험실, 

2층-국어교육과, 수업참관실, 과학영재교육원 행정실, 행정실, 학장실, 

3층-컴퓨터 교육과, 사회교육과, 교육학과

사범대학2호관

1층-사회교육 시청각 강의실, 일반사회교육강의실, 물품분류형태학준비실, 생태학 실험실, 분자유전생물학 실험실, 학생회 사무실, 세포생화학 실험실, 

2층-영어교육과, 영어몰입 강의실, 영미문화 강의실, 수학교육과, 전산실습실, 

3층-임용고사 준비실, 교육학과 세미나실, 수업행동 분석실, 윤리교육과, 과제 독서실, 


![인문대1호관](https://user-images.githubusercontent.com/26293574/104823406-2e93c000-588d-11eb-885b-e00bea19a311.jpg)

인문대학 1호관

1층-국어국문학과 사무실, 영어영문학과 사무실, 독일학과 사무실, 일어일문 사무실, 중어중문 사무실, 사학과 사무실, 사회학과 사무실, 철학과 사무실, 학생회 사무실, 여학생 휴게실, 매점

2층-국문/영문/독일/일문/중문/사학/사회/철학 감사연구실, 한국사회과학연구지원사업단, 문화사랑방, 복합회의실, 인문과학 연구소, 대학원 세미나실, 행정실, 학장실, 인문학 자료실, 탐라 문화연구원, 문서고, 국어 문화원 제주어 센터

3층-간호학 강의실, MCE멀티미디어 실습실, 소리어울림음악멘토링센터, 교육학과, 예술디자인 대학 학생회, 한국학 협동과정, 한국학 자료센터


![수의대학](https://user-images.githubusercontent.com/26293574/104823416-39e6eb80-588d-11eb-8a5f-632b3e00f354.jpg)

수의 대학

B1층- 학생회, 학생휴게실, 병리부검실, 형태학 실습실, 전기실, 기계실

1층-도서관, 학과사무실, 세미나실, 대강당

2층-교수회의실, 행정실, 자료실, 학장실, 조직병리실, 병원체검사실, PCR검사실

3층-조직학실험실, 약리학 실험실, 미생물학 실험실, 공중보건학 실험실, 외과학실험실, 영상진단학실험실, 저온실, 방사선동위원소실

4층-산과학 실험실, 해부학실험실, 생리학실험실, 반려동물내과학실험실, 공동기기실, 독성학 실험실, 생화학실험실, 기생충학실험실, 예방수의학 실험실, 말번식 실험실, 말 임상학 실험실

![평생교육원](https://user-images.githubusercontent.com/26293574/104823431-4bc88e80-588d-11eb-958a-330f47f82019.jpg)

평생교육원

강의실


![중앙디지털도서관](https://user-images.githubusercontent.com/26293574/104823432-52ef9c80-588d-11eb-8916-c5e6a05f75da.jpg)

중앙디지털도서관

1층-미디어 라운지, 유니버셜라운지, 인포메이션데스크, 커뮤니티홀

2층-그룹스터디 라운지, 국내서 2자료실

3층-국내서 1자료실, 라이브러리홀

![아라컨벤션홀](https://user-images.githubusercontent.com/26293574/104823439-5a16aa80-588d-11eb-9d39-e333e094c800.jpg)
![아라컨벤션게스트하우스](https://user-images.githubusercontent.com/26293574/104823441-5d119b00-588d-11eb-9983-de9ebbac2903.jpg)


아라컨벤션홀

1층-대회의실, 세미나실1,2,3, 야외휴게실

2층,3층-게스트 하우스

![교수회관](https://user-images.githubusercontent.com/26293574/104823442-63a01280-588d-11eb-94b7-1330347cc737.jpg)


교수회관

1층-교수회관 식당

2층-제주어연구센터, 해양문화연구센터, 제주사회문화조사연구센터, 제주문화컨텐츠연구센터, 동아시아문화교류 연구센터, 제주4.3연구센터


![중앙도서관](https://user-images.githubusercontent.com/26293574/104823448-6a2e8a00-588d-11eb-94ac-b855ec396620.jpg)

중앙도서관

B1-보존서고, 기계실, 변천실

1층-제주자료실, 로비, PC존, 보존서고

2층-열람실, 학술정보지원과, 관장실, 과장실, 회의실

3층-열람실, 보존서고, 특수자료실, 전산실

![경상대학2호관](https://user-images.githubusercontent.com/26293574/104823453-71ee2e80-588d-11eb-94d5-ba85b57b89f3.jpg)


경상대학 2호관

1층-강의실, 경영대학원 공개강좌과정 강의실, 원생회실, 경상대학 1호관 연결 복도

2층-통합행정실, 부속실, 학장실, 세미나실, 영사실

3층-교수님들 실


![경상대1호관](https://user-images.githubusercontent.com/26293574/104823456-7581b580-588d-11eb-8cb6-c542de855389.jpg)

경상대학 1호관

1층-학생회 사무실, 강의실, 매점, 외국인 유학생 세미나실, 학생 대의원회 사무실

2층-무역학과, 경제학과, 경영학과, 회계학과, 관광경영, 관광개발, 영영정보 사무실, 취업상담실, GIS사업단, 전산시스템실, 제주신화월드 청년아카데미과정 교육실

3층-전산실습실, 강의실, 창의실습실, 과제도서실, 대학원 강의실, 강사공동 연구실, 관광과 경영경제 연구소, 강의실,

그 외

![동물병원](https://user-images.githubusercontent.com/26293574/104823460-87635880-588d-11eb-8e22-7625526160ef.jpg)
동물병원

![의료융합기술센터](https://user-images.githubusercontent.com/26293574/104823465-8fbb9380-588d-11eb-837e-c8e991e0575c.jpg)
의료융합기술센터

![제주골프아카데미](https://user-images.githubusercontent.com/26293574/104823469-977b3800-588d-11eb-8e1a-78540485a812.jpg)
제주 골프 아카데미

![예술디자인대학미술관](https://user-images.githubusercontent.com/26293574/104823476-a06c0980-588d-11eb-80cd-5479868f1668.jpg)
예술디자인대학 미술관
